services:
  elasticsearch:
    image: elasticsearch:9.1.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:9.1.0
    container_name: kibana
    ports:
      - 5601:5601
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./ollama-data:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0

  # model-puller:
  #   image: curlimages/curl:latest
  #   container_name: ollama-model-puller
  #   depends_on:
  #     - ollama
  #   command: >
  #     sh -c "
  #     echo 'Waiting for Ollama service to be ready...' &&
  #     sleep 15 &&
  #     echo 'Pulling gemma2:2b model via API...' &&
  #     curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"gemma2:2b\"}' -H 'Content-Type: application/json' &&
  #     echo 'Model pull request sent successfully!'
  #     "