services:
  elasticsearch:
    image: elasticsearch:9.1.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:9.1.0
    container_name: kibana
    ports:
      - 5601:5601