

INSERT INTO main_categories (name) VALUES
('Development'),
('Business'),
('Design'),
('Marketing'),
('Music'),
('Photography'),
('Health & Fitness'),
('Personal Development'),
('IT & Software'),
('Office Productivity'),
('Teaching & Academics'),
('Lifestyle'),
('Finance & Accounting'),
('Language Learning'),
('Engineering'),
('Data Science'),
('Manufacturing'),
('Sales'),
('Arts & Crafts'),
('Test Preparation');




INSERT INTO subcategories (main_category_id, name) VALUES
(1, 'Web Development'),
(1, 'Mobile Development'),
(1, 'Game Development'),
(1, 'Programming Languages'),
(1, 'Software Testing'),

(2, 'Entrepreneurship'),
(2, 'Finance'),
(2, 'Management'),
(2, 'Sales'),
(2, 'Operations'),

(3, 'Graphic Design'),
(3, 'UI/UX Design'),
(3, '3D Animation'),
(3, 'Fashion Design'),
(3, 'Interior Design'),

(4, 'Digital Marketing'),
(4, 'SEO'),
(4, 'Content Marketing'),
(4, 'Social Media Marketing'),
(4, 'Branding'),

(5, 'Music Production'),
(5, 'Singing'),
(5, 'Instruments'),
(5, 'Music Theory'),
(5, 'Songwriting'),

(6, 'Portrait Photography'),
(6, 'Landscape Photography'),
(6, 'Photography Fundamentals'),
(6, 'Photo Editing'),
(6, 'Wildlife Photography'),

(7, 'Nutrition'),
(7, 'Yoga'),
(7, 'Mental Health'),
(7, 'Self Defense'),
(7, 'Meditation'),

(8, 'Time Management'),
(8, 'Leadership'),
(8, 'Public Speaking'),
(8, 'Personal Finance'),
(8, 'Creative Writing'),

(9, 'Network & Security'),
(9, 'Cloud Computing'),
(9, 'Hardware'),
(9, 'Operating Systems'),
(9, 'DevOps'),

(10, 'Microsoft Excel'),
(10, 'Microsoft PowerPoint'),
(10, 'Microsoft Word'),
(10, 'Google Workspace'),
(10, 'Project Management'),

(11, 'Math'),
(11, 'Science'),
(11, 'Language Learning'),
(11, 'Test Prep'),
(11, 'Teaching Tools'),

(12, 'Travel'),
(12, 'Crafts'),
(12, 'Magic'),
(12, 'Cooking'),
(12, 'Pets'),

(13, 'Accounting'),
(13, 'Investing'),
(13, 'Taxes'),
(13, 'Cryptocurrency'),
(13, 'Financial Modeling'),

(14, 'Spanish'),
(14, 'French'),
(14, 'German'),
(14, 'Japanese'),
(14, 'Chinese'),

(15, 'Mechanical Engineering'),
(15, 'Electrical Engineering'),
(15, 'Civil Engineering'),
(15, 'Chemical Engineering'),
(15, 'Industrial Engineering'),

(16, 'Machine Learning'),
(16, 'Artificial Intelligence'),
(16, 'Data Analysis'),
(16, 'Big Data'),
(16, 'Statistics'),

(17, 'CAD & CAM'),
(17, 'Quality Control'),
(17, 'Materials Science'),
(17, 'Product Design'),
(17, 'Automation'),

(18, 'Sales Fundamentals'),
(18, 'B2B Sales'),
(18, 'Cold Calling'),
(18, 'Customer Relationship Management'),
(18, 'Negotiation'),

(19, 'Painting'),
(19, 'Drawing'),
(19, 'Sculpture'),
(19, 'Ceramics'),
(19, 'Calligraphy'),

(20, 'SAT Prep'),
(20, 'GRE Prep'),
(20, 'GMAT Prep'),
(20, 'IELTS Prep'),
(20, 'TOEFL Prep'),


(1, 'Data Structures'),
(2, 'Business Analytics'),
(3, 'Typography'),
(4, 'Affiliate Marketing'),
(5, 'DJing'),
(6, 'Wedding Photography'),
(7, 'Pilates'),
(8, 'Motivation'),
(9, 'Cybersecurity'),
(10, 'Email Productivity'),
(11, 'Physics'),
(12, 'Fashion & Style'),
(13, 'Budgeting'),
(14, 'Korean'),
(15, 'Renewable Energy'),
(16, 'Data Visualization'),
(17, 'Lean Six Sigma'),
(18, 'Sales Leadership'),
(19, 'Digital Painting'),
(20, 'Bar Exam Prep'
);