INSERT INTO main_categories (name) VALUES
('Development'),
('Business'),
('Design'),
('Marketing'),
('Music'),
('Photography'),
('Health & Fitness'),
('Personal Development'),
('IT & Software'),
('Office Productivity'),
('Teaching & Academics'),
('Lifestyle'),
('Finance & Accounting'),
('Language Learning'),
('Engineering'),
('Data Science'),
('Manufacturing'),
('Sales'),
('Arts & Crafts'),
('Test Preparation');

INSERT INTO subcategories (main_category_id, name) VALUES
-- Development (Category 1)
(1, 'Web Development'),
(1, 'Mobile Development'),
(1, 'Game Development'),
(1, 'Programming Languages'),
(1, 'Software Testing'),
(1, 'Data Structures'),
(1, 'Database Design'),
(1, 'DevOps & Deployment'),
(1, 'API Development'),
(1, 'Software Architecture'),
(1, 'Version Control'),
(1, 'Algorithms'),
(1, 'Code Review'),
(1, 'Microservices'),
(1, 'Software Documentation'),
(1, 'Debugging Techniques'),

-- Business (Category 2)
(2, 'Entrepreneurship'),
(2, 'Finance'),
(2, 'Management'),
(2, 'Sales'),
(2, 'Operations'),
(2, 'Business Analytics'),
(2, 'Strategic Planning'),
(2, 'Human Resources'),
(2, 'Supply Chain Management'),
(2, 'Risk Management'),
(2, 'International Business'),
(2, 'Business Law'),
(2, 'Customer Service'),
(2, 'Innovation Management'),
(2, 'Organizational Behavior'),

-- Design (Category 3)
(3, 'Graphic Design'),
(3, 'UI/UX Design'),
(3, '3D Animation'),
(3, 'Fashion Design'),
(3, 'Interior Design'),
(3, 'Typography'),
(3, 'Logo Design'),
(3, 'Web Design'),
(3, 'Brand Identity'),
(3, 'Illustration'),
(3, 'Motion Graphics'),
(3, 'Print Design'),
(3, 'Color Theory'),
(3, 'Design Thinking'),
(3, 'User Research'),

-- Marketing (Category 4)
(4, 'Digital Marketing'),
(4, 'SEO'),
(4, 'Content Marketing'),
(4, 'Social Media Marketing'),
(4, 'Branding'),
(4, 'Affiliate Marketing'),
(4, 'Email Marketing'),
(4, 'Video Marketing'),
(4, 'Influencer Marketing'),
(4, 'Marketing Analytics'),
(4, 'Pay-Per-Click Advertising'),
(4, 'Market Research'),
(4, 'Growth Hacking'),
(4, 'Public Relations'),
(4, 'Event Marketing'),
(4, 'Mobile Marketing'),

-- Music (Category 5)
(5, 'Music Production'),
(5, 'Singing'),
(5, 'Instruments'),
(5, 'Music Theory'),
(5, 'Songwriting'),
(5, 'DJing'),
(5, 'Audio Engineering'),
(5, 'Music Composition'),
(5, 'Sound Design'),
(5, 'Music Business'),
(5, 'Electronic Music'),
(5, 'Classical Music'),
(5, 'Jazz'),
(5, 'Music History'),
(5, 'Live Performance'),
(5, 'Music Therapy'),

-- Photography (Category 6)
(6, 'Portrait Photography'),
(6, 'Landscape Photography'),
(6, 'Photography Fundamentals'),
(6, 'Photo Editing'),
(6, 'Wildlife Photography'),
(6, 'Wedding Photography'),
(6, 'Street Photography'),
(6, 'Product Photography'),
(6, 'Fashion Photography'),
(6, 'Documentary Photography'),
(6, 'Architectural Photography'),
(6, 'Food Photography'),
(6, 'Drone Photography'),
(6, 'Studio Lighting'),
(6, 'Photography Business'),
(6, 'Film Photography'),

-- Health & Fitness (Category 7)
(7, 'Nutrition'),
(7, 'Yoga'),
(7, 'Mental Health'),
(7, 'Self Defense'),
(7, 'Meditation'),
(7, 'Pilates'),
(7, 'Weight Training'),
(7, 'Cardio Fitness'),
(7, 'Sports Performance'),
(7, 'Injury Prevention'),
(7, 'Wellness Coaching'),
(7, 'Dance Fitness'),
(7, 'Rehabilitation'),
(7, 'Holistic Health'),
(7, 'Fitness Nutrition'),
(7, 'Stress Management'),

-- Personal Development (Category 8)
(8, 'Time Management'),
(8, 'Leadership'),
(8, 'Public Speaking'),
(8, 'Personal Finance'),
(8, 'Creative Writing'),
(8, 'Motivation'),
(8, 'Goal Setting'),
(8, 'Confidence Building'),
(8, 'Emotional Intelligence'),
(8, 'Career Development'),
(8, 'Life Coaching'),
(8, 'Memory Improvement'),
(8, 'Decision Making'),
(8, 'Habit Formation'),
(8, 'Interpersonal Skills'),
(8, 'Self Reflection'),

-- IT & Software (Category 9)
(9, 'Network & Security'),
(9, 'Cloud Computing'),
(9, 'Hardware'),
(9, 'Operating Systems'),
(9, 'DevOps'),
(9, 'Cybersecurity'),
(9, 'System Administration'),
(9, 'IT Support'),
(9, 'Virtualization'),
(9, 'Database Administration'),
(9, 'Mobile Security'),
(9, 'Blockchain Technology'),
(9, 'Internet of Things'),
(9, 'Software Licensing'),
(9, 'IT Project Management'),
(9, 'Enterprise Architecture'),

-- Office Productivity (Category 10)
(10, 'Microsoft Excel'),
(10, 'Microsoft PowerPoint'),
(10, 'Microsoft Word'),
(10, 'Google Workspace'),
(10, 'Project Management'),
(10, 'Email Productivity'),
(10, 'Data Entry'),
(10, 'Presentation Skills'),
(10, 'Workflow Optimization'),
(10, 'Document Management'),
(10, 'Spreadsheet Analysis'),
(10, 'Office Administration'),
(10, 'Communication Tools'),
(10, 'Remote Work'),
(10, 'Calendar Management'),
(10, 'File Organization'),

-- Teaching & Academics (Category 11)
(11, 'Math'),
(11, 'Science'),
(11, 'Language Learning'),
(11, 'Test Prep'),
(11, 'Teaching Tools'),
(11, 'Physics'),
(11, 'Curriculum Development'),
(11, 'Educational Technology'),
(11, 'Classroom Management'),
(11, 'Learning Disabilities'),
(11, 'Research Methods'),
(11, 'Academic Writing'),
(11, 'Assessment & Evaluation'),
(11, 'Special Education'),
(11, 'Chemistry'),
(11, 'Biology'),

-- Lifestyle (Category 12)
(12, 'Travel'),
(12, 'Crafts'),
(12, 'Magic'),
(12, 'Cooking'),
(12, 'Pets'),
(12, 'Fashion & Style'),
(12, 'Home Organization'),
(12, 'Gardening'),
(12, 'Interior Decorating'),
(12, 'Parenting'),
(12, 'Relationships'),
(12, 'Beauty & Makeup'),
(12, 'Wine & Spirits'),
(12, 'Sustainable Living'),
(12, 'Home Improvement'),
(12, 'Personal Safety'),

-- Finance & Accounting (Category 13)
(13, 'Accounting'),
(13, 'Investing'),
(13, 'Taxes'),
(13, 'Cryptocurrency'),
(13, 'Financial Modeling'),
(13, 'Budgeting'),
(13, 'Financial Planning'),
(13, 'Real Estate Investing'),
(13, 'Insurance'),
(13, 'Retirement Planning'),
(13, 'Estate Planning'),
(13, 'Financial Analysis'),
(13, 'Bookkeeping'),
(13, 'Forensic Accounting'),
(13, 'International Finance'),
(13, 'Risk Assessment'),

-- Language Learning (Category 14)
(14, 'Spanish'),
(14, 'French'),
(14, 'German'),
(14, 'Japanese'),
(14, 'Chinese'),
(14, 'Korean'),
(14, 'Italian'),
(14, 'Portuguese'),
(14, 'Russian'),
(14, 'Arabic'),
(14, 'Hindi'),
(14, 'Dutch'),
(14, 'Swedish'),
(14, 'Polish'),
(14, 'Turkish'),
(14, 'Hebrew'),

-- Engineering (Category 15)
(15, 'Mechanical Engineering'),
(15, 'Electrical Engineering'),
(15, 'Civil Engineering'),
(15, 'Chemical Engineering'),
(15, 'Industrial Engineering'),
(15, 'Renewable Energy'),
(15, 'Software Engineering'),
(15, 'Aerospace Engineering'),
(15, 'Biomedical Engineering'),
(15, 'Environmental Engineering'),
(15, 'Structural Engineering'),
(15, 'Robotics Engineering'),
(15, 'Materials Engineering'),
(15, 'Systems Engineering'),
(15, 'Engineering Ethics'),
(15, 'Engineering Management'),

-- Data Science (Category 16)
(16, 'Machine Learning'),
(16, 'Artificial Intelligence'),
(16, 'Data Analysis'),
(16, 'Big Data'),
(16, 'Statistics'),
(16, 'Data Visualization'),
(16, 'Python for Data Science'),
(16, 'R Programming'),
(16, 'SQL for Data Analysis'),
(16, 'Deep Learning'),
(16, 'Natural Language Processing'),
(16, 'Computer Vision'),
(16, 'Predictive Analytics'),
(16, 'Data Mining'),
(16, 'Time Series Analysis'),
(16, 'Business Intelligence'),

-- Manufacturing (Category 17)
(17, 'CAD & CAM'),
(17, 'Quality Control'),
(17, 'Materials Science'),
(17, 'Product Design'),
(17, 'Automation'),
(17, 'Lean Six Sigma'),
(17, '3D Printing'),
(17, 'Supply Chain Optimization'),
(17, 'Manufacturing Processes'),
(17, 'Industrial Safety'),
(17, 'Production Planning'),
(17, 'Operations Research'),
(17, 'Factory Management'),
(17, 'Inventory Management'),
(17, 'Cost Analysis'),
(17, 'Equipment Maintenance'),

-- Sales (Category 18)
(18, 'Sales Fundamentals'),
(18, 'B2B Sales'),
(18, 'Cold Calling'),
(18, 'Customer Relationship Management'),
(18, 'Negotiation'),
(18, 'Sales Leadership'),
(18, 'Retail Sales'),
(18, 'Online Sales'),
(18, 'Sales Psychology'),
(18, 'Sales Presentations'),
(18, 'Territory Management'),
(18, 'Sales Coaching'),
(18, 'International Sales'),
(18, 'Product Knowledge'),
(18, 'Sales Automation'),
(18, 'Customer Retention'),

-- Arts & Crafts (Category 19)
(19, 'Painting'),
(19, 'Drawing'),
(19, 'Sculpture'),
(19, 'Ceramics'),
(19, 'Calligraphy'),
(19, 'Digital Painting'),
(19, 'Woodworking'),
(19, 'Jewelry Making'),
(19, 'Knitting & Crochet'),
(19, 'Scrapbooking'),
(19, 'Origami'),
(19, 'Pottery'),
(19, 'Quilting'),
(19, 'Embroidery'),
(19, 'Candle Making'),
(19, 'Glass Art'),

-- Test Preparation (Category 20)
(20, 'SAT Prep'),
(20, 'GRE Prep'),
(20, 'GMAT Prep'),
(20, 'IELTS Prep'),
(20, 'TOEFL Prep'),
(20, 'Bar Exam Prep'),
(20, 'MCAT Prep'),
(20, 'LSAT Prep'),
(20, 'CPA Exam Prep'),
(20, 'FRM Exam Prep'),
(20, 'PMP Exam Prep'),
(20, 'CompTIA Certification'),
(20, 'AWS Certification'),
(20, 'CISSP Exam Prep'),
(20, 'Microsoft Certification'),
(20, 'Google Certification');